# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates(GG).p12'
    certPwd: '$(P12password)'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'SampleJenkinsApp_AppStore.mobileprovision'
    removeProfile: false

- task: CmdLine@2
  inputs:
    script: 'security find-identity -p codesigning -v'

- task: CmdLine@2
  inputs:
    script: 'ls /Users/vsts/agent/2.155.1/work/1/s/TimeTable.xcodeproj/'

- task: CmdLine@2
  inputs:
    script: '/usr/bin/xcodebuild -showsdks'

- task: CmdLine@2
  inputs:
    script: '/usr/bin/xcodebuild -version'

- task: CmdLine@2
  inputs:
    script: '/usr/local/bin/fastlane beta'

- task: CmdLine@2
  inputs:
    script: 'cat /Users/vsts/Library/Logs/gym/TimeTable-Timetable.log'
    failOnStderr: false
    
# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     scheme: 'TimeTable'
#     xcodeVersion: '9'
#     packageApp: false
#     signingOption: 'manual'
#     signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
#     provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
#     provisioningProfileName: 'SampleJenkinsApp_AppStore.mobileprovision'
#     destinationPlatformOption: 'iOS'
#     destinationSimulators: 'iPhone 6'

# - task: Xcode@5  
#   inputs:
#     actions: 'build'
#     sdk : ''
#     configuration: '$(Configuration)'
#     scheme: 'TimeTable'
#     xcodeVersion: '10'
#     packageApp: false
#     signingOption: 'manual'
#     signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
#     provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
#     provisioningProfileName: 'SampleJenkinsApp_AppStore.mobileprovision'
#     destinationPlatformOption: 'iOS'
#     destinationSimulators: 'iPhone 6'
# - task: AppStoreRelease@1
#   inputs:
#     serviceEndpoint: 'AppStoreConnect'
#     appIdentifier: 'com.werkztechnologies.sampleenkinsapp'
#     appType: 'iOS'
#     ipaPath: '**/*.ipa'
#     releaseTrack: 'TestFlight'