# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates(4Q).p12'
    certPwd: 'Amdon1012'
    keychain: 'temp'
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'SampleJenkinsApp_AppStore.mobileprovision'
    removeProfile: false
    
# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     configuration: 'Debug'
#     sdk: 'iphoneos'
#     scheme: 'TimeTable'
#     xcodeVersion: '9'
#     packageApp: false
#     signingOption: 'default'
#     destinationPlatformOption: 'iOS'
#     destinationSimulators: 'iPhone 6'

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: '$(CONFIGURATION)'
    scheme: 'TimeTable'
    xcodeVersion: '9'
    packageApp: false
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    provisioningProfileName: 'SampleJenkinsApp_AppStore.mobileprovision'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 6'

# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     sdk: 'iphoneos'
#     configuration: 'Debug'
#     scheme: 'TimeTable'
#     xcodeVersion: '9'
#     packageApp: true
#     signingOption: 'auto'
#     publishJUnitResults: true
- task: AppStoreRelease@1
  inputs:
    serviceEndpoint: 'AppStoreConnect'
    appIdentifier: 'com.werkztechnologies.sampleenkinsapp'
    appType: 'iOS'
    ipaPath: '**/*.ipa'
    releaseTrack: 'TestFlight'

