# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # desc "Push a new beta build to TestFlight"
  # lane :beta do
  # 	match(type: "development", readonly: is_ci)
  #   increment_build_number(xcodeproj: "TimeTable.xcodeproj")
  #   # build_app(scheme: "TimeTable")
  #   gym(scheme: "TimeTable")
  #   upload_to_testflight
  #   push_to_git_remote
  # end

  # before_all do
  #   unlock_keychain(path: '~/Library/Keychains/login.keychain',password: "A1DC2A63B3D14817A64619FDDBC92264")
  # end
  def ensure_temp_keychain(name)
    delete_keychain(
      name: name
    ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
    create_keychain(
      name: name,
      password: 'ggwp',
      unlock: true,
      timeout: false
    )
  end

  lane :beta do
  	ensure_temp_keychain 'fastlane_enterprise'
    match(type: "appstore", readonly: true,keychain_name: 'fastlane_enterprise',keychain_password: 'ggwp')
    increment_build_number(xcodeproj: "TimeTable.xcodeproj")
    gym(
    	scheme: "TimeTable",
    	configuration: "Release",
    	clean: true,
        sdk: "iphoneos",
        export_xcargs: "-allowProvisioningUpdates"
      #destination: "platform=iOS Simulator,name=iPhone 6",
    )
  end


  desc "Run unit and ui tests"
  lane :runTests do
    run_tests(
      scheme: "TimeTable",
      #code_coverage: true 
    )
  end

end
