# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # desc "Push a new beta build to TestFlight"
  # lane :beta do
  # 	match(type: "development", readonly: is_ci)
  #   increment_build_number(xcodeproj: "TimeTable.xcodeproj")
  #   # build_app(scheme: "TimeTable")
  #   gym(scheme: "TimeTable")
  #   upload_to_testflight
  #   push_to_git_remote
  # end

  # Fetch the keychain env variables
  # securely stored in the azure pipeline yml
  keychain_name = ENV["MATCH_KEYCHAIN_NAME"]
  keychain_password = ENV["MATCH_KEYCHAIN_PASSWORD"]

  before_all do
    unlock_keychain(path: '~/Library/Keychains/login.keychain',password: "A1DC2A63B3D14817A64619FDDBC92264")
    clear_derived_data
    # cocoapods(
    #   clean:true
    # )
    # @fastlane_dir = File.expand_path(File.dirname(__FILE__))

    create_keychain(
      name: keychain_name,
      password: keychain_password,
      unlock: true,
      timeout: false,
      default_keychain: true,
      add_to_search_list: true
    )
  end
  # def ensure_temp_keychain(name)
  #   delete_keychain(
  #     name: name
  #   ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  #   create_keychain(
  #     name: name,
  #     password: 'ggwp',
  #     unlock: true,
  #     default_keychain: true,
  #     timeout: false
  #   )
  # end

  lane :beta do
  	# ensure_temp_keychain 'fastlane_enterprise'
    # match(type: "appstore", readonly: true,keychain_name: 'fastlane_enterprise',keychain_password: 'ggwp')
    match(
		type: "appstore",
		keychain_name: keychain_name,
		keychain_password: keychain_password,
		readonly: true,
		verbose: true
	)
    increment_build_number(xcodeproj: "TimeTable.xcodeproj")
    gym(
    	scheme: "TimeTable",
    	configuration: "Release",
    	clean: false,
        sdk: "iphoneos",
        # export_xcargs: "-allowProvisioningUpdates",
        verbose: true
      #destination: "platform=iOS Simulator,name=iPhone 6",
    )
    delete_keychain(
      name: "apk_ggwp"
    )
  end


  desc "Run unit and ui tests"
  lane :runTests do
    run_tests(
      scheme: "TimeTable",
      #code_coverage: true 
    )
  end

end
